---
language: java
jdk: openjdk9

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - mvn install:install-file -Dfile=src/main/resources/rpi-ws281x-java-2.0.0-SNAPSHOT.jar -DgroupId=com.github.mbelling -DartifactId=rpi-ws281x-java -Dversion=2.0.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true

branches:
  only:
    - master
    - /^travis.*/
    - /^v.*/

stages:
  - name: test
  - name: deploy
    if: tag IS present
  - name: deploy snapshot
    if: branch = master AND type != pull_request AND tag IS blank

jobs:
  include:
    - stage: test
      install: skip
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      script: skip
      install: skip
      deploy:
        - provider: script
          script: mvn --settings .maven.xml site -DskipTests=true -B && git add dokka
          on:
            tags: true
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
          on:
            tags: true
    - stage: deploy
      script: skip
      install: skip
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B
          on:
            tags: true
    - stage: deploy snapshot
      script: skip
      install: skip
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B -Dregistry=https://maven.pkg.github.com/AnimatedLEDStrip -Dtoken=$GITHUB_TOKEN
          on:
            branch: master
